.PHONY: create

create:
	# stow -t ~/.config/nvim nvim
	stow -t ~/.config/nvim lzvim
	stow -t ~/.config/kitty kitty
	stow -t ~ wezterm
	stow -t ~ zsh
	stow -t ~ tmux
	
delete:
	# stow -D -t ~/.config/nvim nvim
	# stow -D -t ~/.config/kitty kitty
	stow -D -t ~ wezterm
	stow -D -t ~ zsh
	stow -D -t ~ tmux
